### PR TITLE
Projects Overview

### LINKED ISSUE #24: Add overview of all projects
- [ ] Add AIOps project overviews from [doc](https://github.com/aicoe-aiops/data-science-workflows/blob/master/docs/aiops-projects.md) to operate-first repo.
- [ ] Add overview as an item on left toc, and find a suitable header - probably "Projects Overview"

### PR DESCRIPTION
**Pull request by aakankshaduggal**
This PR adds a document that includes overview of projects with AIOps team. 
Fixes #24

### CODE REVIEW

**Comment by oindrillac** [comment]
@aakankshaduggal you might want to pull from upstream once into your fork. The new format for adding content is `operate-first.github.io/content/name-of-your-dir`. Also you'd have to update the `content/toc.yaml`.  You can follow the steps in the readme to locally test your changes and see if the changes look as expected on the website

**Review by oindrillac — CHANGES_REQUESTED** [review]
Please see comment

**Comment by aakankshaduggal** [comment]
@oindrillac I have made the changes and it works fine locally for me. Please lmk if this needs any changes :smile:

**Review by oindrillac — CHANGES_REQUESTED** [review]
@aakankshaduggal the formatting looks good. Can you add a one line description at the start of the doc on what this list comprises of / what this doc is about?

**Comment by aakankshaduggal** [comment]
> @aakankshaduggal the formatting looks good. Can you add a one line description at the start of the doc on what this list comprises of / what this doc is about?

@oindrillac Done :+1:

**Comment by hemajv** [comment]
@aakankshaduggal maybe you can also point us to your rendered GitHub page so that we can view the changes there as well?

**Comment by aakankshaduggal** [comment]
@hemajv https://aakankshaduggal.github.io/operate-first.github.io/projects-overview

**Review by oindrillac — APPROVED** [review]
LGTM

**Review by hemajv — APPROVED** [review]
:ship:

**Pull request merged**
