### PR TITLE
Index page updates

### PR DESCRIPTION
**Pull request by mcoker**
I configured GP pages to build from this fork and am getting the error:

> The tag `tip` on line 39 in `content/examples/markdown.md` is not a recognized Liquid tag. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.

This PR:

* Adds new styles for the home page -  https://github.com/operate-first/operate-first.github.io/blob/9bf59dc772ec8187d6c2a6af02d1444ae4a7f315/src/components/Layout/Layout.scss#L15-L32
* Adds `ofc-page-section-center` and `ofc-text-center` to the main page content to center the box of content and the text in it. Also adds `isWidthLimited` to keep the page content from expanding to fit the width of the viewport - https://github.com/operate-first/operate-first.github.io/blob/9bf59dc772ec8187d6c2a6af02d1444ae4a7f315/src/templates/Markdown.js#L17
* Adds `ofc-text-center` to the page section with the contribute button to center the button, and moves the dark footer within the page layout as a sticky section to fix its layout - https://github.com/operate-first/operate-first.github.io/blob/9bf59dc772ec8187d6c2a6af02d1444ae4a7f315/src/components/Layout/Layout.js#L24-L33
* Updates the index page with new content - https://github.com/operate-first/operate-first.github.io/blob/9bf59dc772ec8187d6c2a6af02d1444ae4a7f315/content/index.md

cc @tumido

### CODE REVIEW

**Comment by tumido** [comment]
@mcoker thank you for the PR!

I've rendered this page in MarvelApp for people to review and left few comments in there:
https://marvelapp.com/prototype/g9757b4/screen/78687788

Not all the comments apply to your changes, but they contribute to the overall page appearance and I think we should do something about it as well. :slightly_smiling_face: 

cc @durandom @HumairAK please chip in ideas.

Also I don't think the "Key personas" are identified properly (because why should a developer go to Open Infra Labs - they will just point them back here..), but this can be solved later on - let's focus this PR on the design, form and appearance.

**Comment by tumido** [comment]
Btw, my idea for this front page was to look more like ACM or something... Was this planned to be a whole front page rewrite or just keep the changes to minimal?

I'm sorry, I think the initial assignment you've received doesn't match what we've been told to expect probably. :)

For comparison, ACM front page that I think would be also a functional design for our front page:

multicloud-console apps moc-infra massopen cloud_multicloud_welcome

**Comment by durandom** [comment]
This was intended to be a quick update to the landing page, to make it more attractive and convey the message. Since it'll be mentioned at the RH Summit. So let's get this merged quick.

@mcocker is there anything substantial missing or can we merge and then do smaller iterations?

**Comment by mcoker** [comment]
@durandom we iterated on the design initially, and based on that feedback it should be fine to merge at this point and follow up with small changes. The only outstanding items I know of are with the wording of the link text in the persona cards, updating of the avatar images (I used stock ones I found online), and then just making sure the file updates I made in the repo are all in the right place since I'm unfamiliar with the repo file structure.

**Comment by durandom** [comment]
cool I'll merge then :shipit: 
/approve

**Comment by durandom** [comment]
@mcoker awesome, the changes are live. 
2 issues: 

* all the content is centered now - also on the subpages :(
* the images on the frontpage are missing.

**Comment by mcoker** [comment]
> @mcoker awesome, the changes are live.
> 2 issues:
> 
> * all the content is centered now - also on the subpages :(
> * the images on the frontpage are missing.

Thanks! @durandom re: the content centering, would it be possible to conditionally apply the .ofc-text-center class to the page sections on the home page only?

**Comment by tumido** [comment]
Text centering is resolved via https://github.com/operate-first/operate-first.github.io/pull/240

**Pull request merged**
