### PR TITLE
feat: Display a banner from frontmatter

### PR DESCRIPTION
**Pull request by tumido**
A follow up to https://github.com/operate-first/operate-first.github.io/pull/282#pullrequestreview-730695868

This PR enables each page to define a top banner via frontmatter annotation. You can simply pass any markdown/html in there and it gets rendered on top of the page as a full size page section.

This allows us to move the top banner out of the document's `PageSection` flow and move it to a better place.

### Before:
image

### After:
image

/cc @quaid @margarethaley @oindrillac @durandom

### CODE REVIEW

**Review by oindrillac — CHANGES_REQUESTED** [review]
thanks @tumido!! couple of comments

Are you intentionally removing the 2 CTA boxes "I am an open source developer" and "I want to learn SRE practices"?

I think those two white boxes created by @margarethaley made the CTAs very prominent.

And also the vertical whitespace between the Operate First logo, the tagline and the CTAs made them clearly distinguishable, is it possible to keep the vertical indent?

**Comment by tumido** [comment]
Hey @oindrillac 

> Are you intentionally removing the 2 CTA boxes "I am an open source developer" and "I want to learn SRE practices"?
> I think those two white boxes created by @margarethaley made the CTAs very prominent.

Yes, the removal of CTA boxes happened. I've used the inlined CTA style. I'll experiment with the other recommended styles and use a more prominent one.

> And also the vertical whitespace between the Operate First logo, the tagline and the CTAs made them clearly distinguishable, is it possible to keep the vertical indent?

Sure, everything is possible! Let me try adjusting it :slightly_smiling_face:

**Comment by tumido** [comment]
Peek 2021-08-18 11-12

@oindrillac WDYT ^

I think we should be using the accent color for the button text, as it is preferred by Patternfly design guidelines.

https://www.patternfly.org/v4/components/button/design-guidelines#call-to-action-cta-button
They also prefer to have only one CTA per page, and if it can't be avoided to have multiple, they say that we should use 1 primary and the other one secondary colors.. like here:
https://www.patternfly.org/v4/

I've replicated the Patternfly homepage layout, that looks like this:
Peek 2021-08-18 11-13


I'm honestly starting to think that both secondary CTAs look the best though:
Peek 2021-08-18 11-17

What do you think, which is better? :smile:

**Comment by oindrillac** [comment]
@tumido I also like the both secondary CTAs, which turn white upon hovering! lets go with that 🚀

**Comment by tumido** [comment]
@oindrillac updated to both secondary CTAs. :slightly_smiling_face: please review :slightly_smiling_face:

**Review by oindrillac — COMMENTED** [review]
@tumido really like the CTAs now :clap::clap::clap:

A small nit I noticed when I tested this is the difference in sizes of the two boxes under "Interested?" and the slightly off center alignment.

image

Can we move them around to be more like how it is now?

image

**Comment by tumido** [comment]
@oindrillac ohh, nice catch! I didn't notice that! And that's indeed off.

Sure let my try fixing those I think I can even make them use a the Patternfly library `<Tile />` component  instead of custom CSS. :slightly_smiling_face:  Let' me try :slightly_smiling_face:

**Comment by tumido** [comment]
@oindrillac what about this? 
Peek 2021-08-18 22-10

**Review by oindrillac — APPROVED** [review]
Neat! Love it 😍 

/lgtm
/approve

**Pull request merged**
