### PR TITLE
replace custom git clone logic with gatsby plugin

### PR DESCRIPTION
**Pull request by durandom**
Uses https://github.com/stevetweeddale/gatsby-source-git to to essentially the same as the custom git clone logic to pull in remote content.

### CODE REVIEW

**Comment by oindrillac** [comment]
@durandom do you have some recommendations on when do we prefer gatsby-source-git vs git clone for adding remote repos?

**Review by cfchase — APPROVED** [review]
lgtm.  Looks great!

**Comment by durandom** [comment]
> @durandom do you have some recommendations on when do we prefer gatsby-source-git vs git clone for adding remote repos?

I'd like to remove the custom code. Less to maintain

**Comment by oindrillac** [comment]
> > @durandom do you have some recommendations on when do we prefer gatsby-source-git vs git clone for adding remote repos?
> 
> I'd like to remove the custom code. Less to maintain

So for any repos being added, do you recommend going down the gatsby-source-git route ie edit the gatsby-config.js? 
We can update the readme accordingly.

**Comment by tumido** [comment]
@oindrillac  I think we should try converting all the repos using `gatsby-source-git` and use that way only...

**Pull request merged**
