### PR TITLE
fixed blueprint repo urls

### LINKED ISSUE #88: ADR do not render
https://operate-first.github.io/blueprint/docs/adr/0000-use-markdown-architectural-decision-records does not render, even though I tested it locally with the dev.sh script...

/assign @oindrillac
/assign @cfchase  
/kind bug

### PR DESCRIPTION
**Pull request by oindrillac**
modified urls in blueprint toc
my gh pages preview: https://oindrillac.github.io/operate-first.github.io/blueprint/0000-use-markdown-architectural-decision-records

fixes #88 

image

### CODE REVIEW

**Comment by goern** [comment]
Moin, just because you have it open anyways, could you replace "blueprint" by "adr" ?! ;) thanks!

**Comment by oindrillac** [comment]
@goern done :heavy_check_mark:

**Review by goern — APPROVED** [review]
thnaks a lot!

**Pull request merged**
