### PR TITLE
Add categorical encoding blog

### LINKED ISSUE #5: Add one open source data science blog post to this repo
This should be the basis for proving this `post` -> `notebook render` -> `notebook deploy` workflow.

So maybe we can choose one where we already have a good notebook and jupyterhub image for

### PR DESCRIPTION
**Pull request by Shreyanand**
In this PR, I add the blog and the corresponding images for the categorical encoding project.

### CODE REVIEW

**Comment by durandom** [comment]
@Shreyanand did you check if the post is rendered nicely and shows up in the navigation?

**Comment by Shreyanand** [comment]
@durandom I build the site locally and made changes to the toc.yaml file as well to make it show up in the navigation. It renders fine on my local. @cfchase do I need to make any other change?

**Review by cfchase — APPROVED** [review]
Looks good to me.

**Comment by cfchase** [comment]
Inclusion of things like dates and tags probably indicate I have some work items to add those fields to the frontmatter to display them in a nice way.

https://github.com/operate-first/operate-first.github.io/issues/18

We could also implement some sort of document search to index the docs and tags if that interests @durandom

**Comment by oindrillac** [comment]
:+1: for document search @cfchase

**Review by durandom — APPROVED** [review]
👍

**Pull request merged**
