### PR TITLE
remove redirect of index page and link logo to /

### PR DESCRIPTION
**Pull request by durandom**
moving the operate first content to the index page.

### CODE REVIEW

**Comment by durandom** [comment]
fixes https://github.com/operate-first/operate-first.github.io/issues/97

**Comment by durandom** [comment]
@cfchase any idea why this `index.mdx` page does not get the default layout?

image

**Comment by durandom** [comment]
@cfchase I did it \o/

**Comment by durandom** [comment]
fixes #71

**Review by durandom — COMMENTED** [review]
/approve

**Comment by cfchase** [comment]
fixes https://github.com/operate-first/operate-first.github.io/issues/97

**Pull request merged**
