### PR TITLE
adding github-labeler project

### LINKED ISSUE #319: Add github-labeler blog to opf website
For the project [github-labeler](https://github.com/aicoe-aiops/github-labeler), add the project description and blog to the Data Science Projects

- [x] Create an addition to the existing [projects' document](https://github.com/operate-first/operate-first.github.io/blob/master/content/data-science/projectsoverview.md) 

- [x] Link the blog to the description

cc- @MichaelClifford @antter

### PR DESCRIPTION
**Pull request by antter**
Added github-labeler to project list, blog link is now active

Fixes #319

### CODE REVIEW

**Review by aakankshaduggal — COMMENTED** [review]
Could you please add this in alphabetic order?

**Comment by antter** [comment]
> Could you please add this in alphabetic order?

done!

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm
/approve

**Review by oindrillac — APPROVED** [review]
/approve

**Pull request merged**
