### PR TITLE
Add documentation to Pulp instance

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
A friendly ping, could this be reviewed? Thanks in advance.

**Review by tumido — COMMENTED** [review]
hey @fridex thanks for the PR.

Your changes will add the docs from your repo to the website container, however in order for it to be displayed in any of the menus on the website, you need to add the anchors in here as well:
https://github.com/operate-first/operate-first.github.io/blob/master/config/users.yaml

If you leave the PR as is, the docs will be accessible under a direct link, so it's like if you know the proper link, you can see it but it's not present in any navigation.

Do you want to change this or is the current setup enough for you?

**Comment by fridex** [comment]
@tumido thanks for the review, adjusted in 428870793

**Comment by fridex** [comment]
@tumido gently ping, is there anything more needed from my side to get this in?

**Review by oindrillac — APPROVED** [review]
/lgtm 👍 
/approve

**Review by harshad16 — COMMENTED** [review]
/lgtm

**Pull request merged**
