### PR TITLE
Add emphasis on "working in the open"

### PR DESCRIPTION
**Pull request by gsaslis**
Not everyone in the broader community is familiar with Red Hat's "upstream first" philosophy, so this PR offers a little more background and puts more emphasis on the "working in the open" part.

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm
/cc @durandom @HumairAK

**Comment by tumido** [comment]
Thank you @gsaslis! This was certainly missing on that page. :slightly_smiling_face:

**Comment by durandom** [comment]
cc @billburnseh WDYT?

**Comment by billburnseh** [comment]
Looks good to me, One of the tenets of operate first is that it relates to or joins upstream first as a way we do things.

**Review by HumairAK — APPROVED** [review]

**Pull request merged**
