### PR TITLE
Update invalid links, and update outdated info.

### PR DESCRIPTION
**Pull request by HumairAK**
This pr introduces cleaning up some invalid links, and updating existing content that's a bit outdated. I've also done a bit of minimal changes to organization. In summary: 

- Remove `continuous-deployment` docs, some were outdated (and removed in the corresponding repo), while others are found else where and linked under the users > argocd section.
- Also re-organized the "Onboarding" section, since it's not really clear what a user can find under this section, I've split this up into: 
    - `Users > ArgoCD`
    - `Users > MOC `
    - `Users > General FAQ `
 - What was previously `Users > MOC` has been renamed to `Operate First Support` since it links to the readme at `operate-first/support` and is thus more accurate
 - I renames `Operators` to `Operations` so it's more clear, and not to be confused with k8s operators 
 - Added the toolbox readme to `Operations > Toolbox` 
 - Added GIthub alerts, and incident management to `Operations > SRE` section. 
 - Clarified the distinction between "Requesting" and "Self Servicing" onboarding/access for Clusters and ArgoCD (see `Users>MOC` and `Users>ArgoCD`
- Added kafka runbook at `users>kafka>troubleshooting` in the same vein as the JH runbook.

### CODE REVIEW

**Comment by HumairAK** [comment]
What the users section now looks like: 

image

**Comment by HumairAK** [comment]
Operations section: 
You'll notice I've updated the Operations page content as well, to be more generic and not mention ODH specifically.

image

**Comment by HumairAK** [comment]
@tumido @durandom @4n4nd

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Review by oindrillac — COMMENTED** [review]
/lgtm nice changes 👍 
small nit - @HumairAK can you change "operators" to "operations" at this [one remaining place](https://github.com/operate-first/operate-first.github.io#site-structure), on the readme?

**Comment by HumairAK** [comment]
@oindrillac updated

**Review by tumido — APPROVED** [review]
Good cleanup, sensitive and thoughtful changes. I like it. :+1:

/lgtm
/approve

**Pull request merged**
