### PR TITLE
feat: Add onboarding docs and update ADRs

### PR DESCRIPTION
**Pull request by tumido**
Also includes links to pending PRs:
- https://github.com/operate-first/support/pull/49
- https://github.com/operate-first/support/pull/50
- https://github.com/operate-first/blueprint/pull/21

Once those PRs are merged the pages will be accessible.

### CODE REVIEW

**Comment by oindrillac** [comment]
> /hold wait for the pending content PRs

@tumido is this PR ready to unhold?

**Comment by tumido** [comment]
@oindrillac you are :100: right! It is indeed :+1: 

/unhold

**Review by HumairAK — APPROVED** [review]

**Review by oindrillac — APPROVED** [review]
LGTM! :zap::+1:

**Pull request merged**
