### PR TITLE
refactor: Simplify gatsby-node for performace

### LINKED ISSUE #268: detect bad HTML to prevent notebook renderer from failing
We faced an issue (#267) with the line breaks in external notebooks which are added to the site to be detected as bad HTML which cause our notebook renderer to error out resulting in a build fail. We need to include a plugin which automatically detects occurrences of bbad HTML.

> **Gage Krumbach wrote:**
> in the long run there should probably be some plugin that detects bad HTML. I saw that the newer version of the notebook renderer recommended to use one. Especially if the notebooks are being pulled from external sources
> 
cc: @Gkrumbach07

### PR DESCRIPTION
**Pull request by tumido**
Depends on #312
Part of: #296

This PR:
- Fully refactors the `gatsby-node.js` to provide performance boost as well as remove duplicit code
- Improves build time logs by reporting node and page creations

Sample build:

https://user-images.githubusercontent.com/7453394/137203737-3ae93f1e-b06e-4f52-8526-022f74afcbcc.mp4

`info node created <URL>` entries mean that a file was noticed by Gatsby - this file should be served on the `URL`
`info page created <URL>` entries mean that the file was rendered into a page on given `URL`

/hold

### CODE REVIEW

**Comment by durandom** [comment]
❤️ this. Finally, it's getting faster. I thought it's so slow because of the many repositories we include.

**Review by isabelizimm — APPROVED** [review]
/lgtm 
looks fabulous! 🤩

**Pull request merged**
