### PR TITLE
Updated OpenShift broken link on project README

### PR DESCRIPTION
**Pull request by banstack**
### Issue:
This PR resolves issue  [#343](https://github.com/operate-first/operate-first.github.io/issues/343)

### Link used is:
https://www.redhat.com/en/technologies/cloud-computing/openshift

Let me know if a better link should be used or any changes should be made

### CODE REVIEW

**Review by oindrillac — COMMENTED** [review]
Are we still supporting deploying the site on OpenShift? I think with https://github.com/operate-first/operate-first.github.io/pull/312, we removed scripts that support container builds.

I think we should just remove OpenShift and keep only Github pages.

**Comment by banstack** [comment]
Sounds good I'll make the changes

**Review by oindrillac — APPROVED** [review]
/lgtm

Thanks @bryanmontalvan

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
