### PR TITLE
Re-design of the home page

### PR DESCRIPTION
**Pull request by margarethaley**
This pr implements a new design for the site's home page (see image below) and is the implementation of the work done on https://github.com/operate-first/community/issues/37.

Concerning the new CTAs at the top of the page:
* The developer button links to the [MOC Get Started page](https://www.operate-first.cloud/users/support/docs/intro.md), which already exists on the site.
* The SRE button links to [this page](https://www.operate-first.cloud/operations/sre/), which is published to the site but only accessible by direct link. I added this page to the side panel under Operations > SRE > Overview.
* I will make PRs to both the support and SRE repos making minor changes to these two files, just to make the flow a bit smoother from the home page.

@oindrillac and @tumido, can you please take a look and make sure everything looks okay? I've had some problems with the local builds and gh-pages, and I definitely want to make sure I won't break the site :)

**Some things to note:**
* When I run `make dev` locally, the site builds (almost) perfectly. The logo I added at the top of the home page sometimes renders correctly, and other times just shows up as a white box.
* The [gh-pages build](https://margarethaley.github.io/operate-first.github.io/front-pg/) has more issues: I am building from a branch (the [front-page branch](https://github.com/margarethaley/operate-first.github.io/tree/front-pg)) by running `make gh-pages-branch`. I have the same white box problem again, and in addition to that, the buttons and links on the home page don't work. I believe this is just a path issue because operate-first.github.io/front-pg is getting dropped in the urls. For example, the "I am an open source developer button" takes you to https://margarethaley.github.io/users/support/docs/intro.md and gives a 404 error, but if you go to https://margarethaley.github.io/operate-first.github.io/front-pg/users/support/docs/intro.md then you will find the correct page. I just want to verify that the links will work on the actual site.

An image of what the local build looks like (when the logo renders properly):
Screenshot from 2021-08-05 09-45-36

### CODE REVIEW

**Comment by quaid** [comment]
I'm happy with the look and feel, I'm just nervous with Margaret that we don't have a way to operate first with this dev process, so we don't know if it's going to break and nowhere to test and prove. I'll not add approval, hopefully others can confirm better than I.
/lgtm

**Review by oindrillac — COMMENTED** [review]
@margarethaley love the changes! :heart: 

the site doesnt break for me, however I also see the same issue with the logo. Will let @tumido confirm. Will using a vector image help?

**Comment by quaid** [comment]
> @margarethaley love the changes! heart
> 
> the site doesnt break for me, however I also see the same issue with the logo. Will let @tumido confirm. Will using a vector image help?

Now that we can view the site rendered live, the behavior is repeatable—every page refresh, there is a flash where you either see the logo properly or you see the word `LOGO`, then the white box appears.

https://margarethaley.github.io/operate-first.github.io/front-pg/

This looks to me like the CSS layer is making the box appear. It could fix itself when the new code is in the proper location and being served from operate-first.github.io. It would still be a good idea to figure out what is happening. This may affect more than testing the website.

@tumido Do you see the behavior? Do you have ideas for what is going on here?

Do you want to go ahead and push the new front page, and see if it happens in the full production environment? We can always roll back the change if it's happening. But it could be an informative troubleshooting step.

**Comment by quaid** [comment]
Until we have a plan for figuring this out and/or proceeding with troubleshooting, I am going to ...
/remove-lgtm

**Comment by rbo** [comment]
For me it looks broken too.

<details>
  <summary>Screenshot</summary>
  
image

</details>

It looks like the problem is the css `box-shadow`, if I disable/remove the box-shadow setting on the image it looks fine for me:
<details>
  <summary>Screenshot</summary>
  
image

</details>

Here is my [fork](https://github.com/rbo/operate-first.github.io/tree/front-pg) with an fix, added `backgroundColor: 'transparent',`  to gatsby-remark-images.  https://github.com/rbo/operate-first.github.io/commit/aad0c90bc4190de0ecd854c6b175adbe5340bbe7 

Preview: https://rbo.github.io/operate-first.github.io/front-pg

**Comment by quaid** [comment]
> 
> It looks like the problem is the css `box-shadow`, if I disable/remove the box-shadow setting on the image it looks fine for me:

There ya go! And I can't believe I completely forgot about using the browser CSS developer extensions to walk the live CSS for troubleshooting, I haven't had to do that in ... a long time. :) So thank you double for the reminder of that method.

@margarethaley do you want to merge in the changes from @rbo ?

**Comment by margarethaley** [comment]
Just made the change and tested it locally, thanks so much for figuring that our @rbo! Now that everything seems to be working, do you guys want to take another look?
/assign @tumido 
/assign @oindrillac 
/assign @quaid

**Comment by quaid** [comment]
> Just made the change and tested it locally, thanks so much for figuring that our @rbo! Now that everything seems to be working, do you guys want to take another look?
> /assign @tumido
> /assign @oindrillac
> /assign @quaid

I don't have a way of seeing the change, can you push to https://margarethaley.github.io/operate-first.github.io/front-pg/ ?

Regardless, I feel like this is the right answer and would like to see this deployed asap.

Can anyone else test? Or be willing to push it live and roll it back if it doesn't work?

**Review by quaid — COMMENTED** [review]
/lgtm

**Review by tumido — COMMENTED** [review]
I can confirm the build/render works fine now and shows expected content.

@margarethaley I have a nosy question though.. Why did you choose to create a black rectangle on white background on gray background? Wouldn't it be nicer to create a separate (black) banner over the whole page width instead?

Did you choose the current visual intentionally or is that because of our current components/rendering limitations of our Gatsby setup?

**Review by oindrillac — COMMENTED** [review]
Visually changes look good to me! 👍 
/lgtm

**Comment by quaid** [comment]
@tumido you know, that's a good question about where the design came from. @margarethaley is on vacation, so we may have to wait to hear from her, but I know that when I saw it the first time the design made sense to me and I guess I presumed why this style.

I'm not sure about the grey box/band, that may be unintentional from the <div>s chosen. But the central area with logo, short message, and calls to action (CTAs) may have been influenced by other community project designs:

https://sssd.io/
https://www.centos.org/
https://www.rdoproject.org//
http://opendatahub.io/

What I really want to do is get some discussions going around site design and information architecture, which we'll get going on the new open community mailing list, and we can invite some designers and UX folks to join the conversation too.

**Comment by quaid** [comment]
OK, let's roll this up, then out.
/approve

**Comment by tumido** [comment]
@quaid ahh, I didn't notice her PTO, sorry for that. Yes, let's move forward with this :slightly_smiling_face: 

>  the central area with logo, short message, and calls to action (CTAs) may have been influenced by other community project designs

Yup yup. I think it's totally a step in the right direction. :slightly_smiling_face: I followed the same design pattern in my [Meteor Shower website](http://meteor-shower-aicoe-meteor.apps.zero.massopen.cloud/) redesign few days ago. I was just curious if I can help push it even further or if there's intention behind the current design :slightly_smiling_face:

**Comment by margarethaley** [comment]
@tumido @oindrillac @quaid sorry for the delay (as Karsten mentioned, I was on vacation), but thank you all for the help! I love the changes/updates with the banner and CTAs. It is so cool to be able to see this live on the site!!

**Pull request merged**
