### PR TITLE
Canonical URL for our CoC

### PR DESCRIPTION
**Pull request by quaid**
Although the community is using a code of conduct located on another
domain, this lets us have a forever-URL we can always use, then either
use as a land-and-bounce page, or replace with any future CoC we
create.

Signed-off-by: Karsten Wade <kwade@redhat.com>

### CODE REVIEW

**Comment by quaid** [comment]
> Although the community is using a code of conduct located on another
> domain, this lets us have a forever-URL we can always use, then either
> use as a land-and-bounce page, or replace with any future CoC we
> create.

That is, I intend that this content be displayed at https://operate-first.cloud/code_of_conduct ...

And maybe that should be code_of_conduct.html? But that's not pretty.

OK, I think I need to fix this and create a sub-dir of `code_of_conduct` and then an `index.md` with this content.

**Review by tumido — CHANGES_REQUESTED** [review]
I like the idea of having a forever url. What do you think that instead of showing users a blank page with a single link we would rather redirect users to the CoC directly?

See:
https://github.com/operate-first/operate-first.github.io/blob/master/content/operations/alerts.md

```md
---
title: Alerts
description: "Prometheus Alerts"
redirect: https://github.com/operate-first/alerts/issues
---

All alerts are sent to the `operate-first/alerts` repository. You can find them [here](https://github.com/operate-first/alerts/issues).
```

The `redirect` key in `frontmatter` section is used to redirect users directly, in the meantime the content bellow is displayed.


Even if we decide not to redirect, the page should have a `title` and a `description` in the frontmatter.

**Comment by quaid** [comment]
> I like the idea of having a forever url. What do you think that instead of showing users a blank page with a single link we would rather redirect users to the CoC directly?

Oh, that makes sense—we continue with a canonical URL on our domain, and the redirect is in the page so easily replaceable if we're making changes.

> The `redirect` key in `frontmatter` section is used to redirect users directly, in the meantime the content bellow is displayed.
> 
> Even if we decide not to redirect, the page should have a `title` and a `description` in the frontmatter.

Oh, yes, thank you. Which is making me realize we need to add a `frontmatter` section for Community Guide pages so we can serve the Guide as part of the website.

**Review by tumido — APPROVED** [review]
/lgtm
/approve

:+1:

**Pull request merged**
