### PR TITLE
feat: Add console launcher

### PR DESCRIPTION
**Pull request by tumido**
I've got tired a bit of pointing users to the right console. This should help:

Peek 2021-07-22 18-01

cc @HumairAK @hemajv @4n4nd @durandom @oindrillac @margarethaley @quaid

### CODE REVIEW

**Review by 4n4nd — COMMENTED** [review]
/lgtm

This looks awesome! Thanks!

**Review by hemajv — APPROVED** [review]
love it! :heart_eyes: 
/lgtm

**Review by oindrillac — COMMENTED** [review]
/lgtm very cool ❤️

**Review by aakankshaduggal — COMMENTED** [review]
Looks amazing 😍 
/lgtm

**Comment by HumairAK** [comment]
YES this is great, well done! 
/lgtm
/approve

**Pull request merged**
