### PR TITLE
Change code blocks' backgroung to white.

### PR DESCRIPTION
**Pull request by martinpovolny**
Code blocks should have a different color to the default background.

Before:
bef-2020-09-21_20-13

After:
aftr-2020-09-21_20-13

### CODE REVIEW

**Review by oindrillac — COMMENTED** [review]
looks neat @martinpovolny  :+1:

**Comment by oindrillac** [comment]
ping: @cfchase

**Comment by durandom** [comment]
I like it. Let's wait if @cfchase has comments on where to put the CSS

**Comment by martinpovolny** [comment]
> I like it. Let's wait if @cfchase has comments on where to put the CSS

https://www.gatsbyjs.com/docs/global-css/

**Comment by cfchase** [comment]
Looking at the [doc](https://www.gatsbyjs.com/docs/global-css/#adding-global-styles-with-a-layout-component), we've got a [layout component](https://github.com/operate-first/operate-first.github.io/blob/master/src/components/Layout/Layout.scss).  I don't see a downside to putting css there until we have a reason for a global.css.  (I really need to change these filenames to lowercase).

I like it, but I was going to change the background of the actual page to white similar to [this patternfly demo](https://www.patternfly.org/v4/demos/primary-detail/react/primary-detail-full-page/) and then it would match again...  We might also want to change the prismjs theme to one you guys like.  Some of them like VS already have a white background.

included https://prismjs.com/
maybe I can add?: https://github.com/PrismJS/prism-themes

**Comment by durandom** [comment]
@cfchase since we want a similar style like opendatahub.io and the ODH UI, can maintain the style in a separate repo and just add overrides here?
E.g. reference the CSS from gh.com/opendatahub

**Comment by martinpovolny** [comment]
I do not really care how, but I'd really like the code samples to be visually different from the text around. So if you do it otherwise feel free to close this PR.

Just make it different ;)

**Comment by cfchase** [comment]
> I do not really care how, but I'd really like the code samples to be visually different from the text around. So if you do it otherwise feel free to close this PR.
> 
> Just make it different ;)

Ok, let me know what you think about https://github.com/operate-first/operate-first.github.io/pull/29

Screenshot from 2020-09-23 17-35-47

**Pull request closed without merging**
