### PR TITLE
modifying ai-4-ci directory structure

### PR DESCRIPTION
**Pull request by oindrillac**
addresses https://github.com/aicoe-aiops/ocp-ci-analysis/issues/258

## This introduces a breaking change

- [x] Yes
- [ ] No

Please merge only after https://github.com/aicoe-aiops/ocp-ci-analysis/pull/262.

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by isabelizimm — APPROVED** [review]
lgtm!

**Review by tumido — APPROVED** [review]
/approve

**Pull request merged**
