### PR TITLE
added kpi metric notebooks

### LINKED ISSUE #187: notebooks rendered on the website

### PR DESCRIPTION
**Pull request by oindrillac**
Here, I add all ocp-ci KPI Notebooks to the Website.

Resolves https://github.com/aicoe-aiops/ocp-ci-analysis/issues/187

As a result of this, the KPI notebooks should appear on the side panel like:

image

### CODE REVIEW

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm

**Comment by MichaelClifford** [comment]
@oindrillac Do we want to have all of the notebooks discoverable through the side panel like that? I'm worried it might get a little crowded. If we just add the relative links to the KPI document, will the notebooks still render on the website?

**Comment by oindrillac** [comment]
@MichaelClifford yes, that's a good point. yes, they should still render nonetheless. The side panel is indeed getting pretty crowded. I will close this PR out.

**Comment by MichaelClifford** [comment]
@oindrillac Thanks!

**Pull request closed without merging**
