### PR TITLE
feat: Add HeaderTools with YouTube/Github/Slack links

### LINKED ISSUE #213: Link YouTube Channel from Website
Link the YouTube channel from Website. 
Add YouTube icon to Top right corner on the Masthead of the Website which links to the channel or add a separate Videos/Blog page.

### PR DESCRIPTION
**Pull request by tumido**
Resolves: #213 

Add links to masthead

### Before 
image

### After
image

### CODE REVIEW

**Comment by HumairAK** [comment]
tested and works
/lgtm

**Review by oindrillac — COMMENTED** [review]
/lgtm :+1:

**Pull request merged**
