### PR TITLE
Added data skipping section to data-science

### PR DESCRIPTION
**Pull request by oshritf**
Adding doc following https://github.com/operate-first/apps/pull/744

@durandom @erikerlandson

### CODE REVIEW

**Review by oindrillac — CHANGES_REQUESTED** [review]
Hey @oshritf, on testing the site locally it looks like the image on the top of the Overview page does not render.

image

I would recommend removing the <center> tags [like](https://github.com/oindrillac/xskipper/blob/master/site/docs/concepts/data-skipping.md).

which renders the image correctly

image

**Comment by oshritf** [comment]
@oindrillac  updated

**Review by oindrillac — APPROVED** [review]
@oshritf thanks!
/lgtm
/approve

**Pull request merged**
