### PR TITLE
Add redirect from /telemetry to the OpenInfralabs page

### PR DESCRIPTION
**Pull request by durandom**
because we might mention https://www.operate-first.cloud/telemetry at RH summit and it should redirect to the landing page for the telemetry WG at https://openinfralabs.org/telemetry/

### CODE REVIEW

**Comment by durandom** [comment]
@oindrillac I don't know why it doesn't work though :(

any ideas?

```
❯ curl http://localhost:8000/blueprints
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting</title>
</head>
<body>
<pre>Redirecting to <a href="/blueprints/">/blueprints/</a></pre>
</body>
</html>

❯ curl http://localhost:8000/telemetry
<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><link data-identity="gatsby-dev-css" rel="stylesheet" type="text/css" href="/commons.css"/><meta name="note" content="environment=development"/><style type="text/css">
```

**Review by tumido — COMMENTED** [review]
/lgtm

**Comment by oindrillac** [comment]
@durandom I get the following

```
[ochatter@ochatter operate-first.github.io]$ curl http://localhost:8000/blueprints
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting</title>
</head>
<body>
<pre>Redirecting to <a href="/blueprints/">/blueprints/</a></pre>
</body>
</html>
[ochatter@ochatter operate-first.github.io]$ curl http://localhost:8000/telemetry
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting</title>
</head>
<body>
<pre>Redirecting to <a href="/telemetry/">/telemetry/</a></pre>
</body>
</html>

```
however, i dont actually see the redirects on my local browser, or on my github pages fork. I think this is an issue with previewing local redirects. 

the config has `redirectInBrowser: true`, I'm not sure yet why this is an issue.

**Review by oindrillac — APPROVED** [review]
:+1:

**Pull request merged**
