### PR TITLE
Edits/addition to Operations page

### LINKED ISSUE #260: Clarify information on the Operations page for users
Information on the Operations page could be slightly more polished in order to appeal to users. I want to make sure the page is easy to read / understand and provides a simple explanation of what can be found in the tabs. 

- improve phrasing/grammar
- make the meaning of GitOps more explicit
- link to more info on GitOps if the user wants to learn more
- add toolbox heading and info to main page

### PR DESCRIPTION
**Pull request by margarethaley**
This pr adds various edits on the Operate First Operations page. It also provides a bit more information on GitOps and a section for the Operate First toolbox, as well as some links to corresponding pages. Please pay special attention to the toolbox section as I want to make sure that my description is accurate.
Resolves https://github.com/operate-first/operate-first.github.io/issues/260

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Comment by tumido** [comment]
/cc @quaid

please review

/hold for you

**Review by oindrillac — COMMENTED** [review]
/lgtm 👍

**Review by tumido — APPROVED** [review]
Let's not wait with this anymore :slightly_smiling_face: 

/unhold

**Pull request merged**
