### PR TITLE
Configurable content directories

### PR DESCRIPTION
**Pull request by cfchase**

### CODE REVIEW

**Comment by cfchase** [comment]
Supports https://github.com/operate-first/operate-first.github.io/issues/9.  Submodule or subtree PR to follow.

**Comment by durandom** [comment]
@cfchase does this PR already add support to include remote content repos? Or will that be a feature with the upcoming PR?

**Comment by cfchase** [comment]
> @cfchase does this PR already add support to include remote content repos? Or will that be a feature with the upcoming PR?

So this should support it already as you could configure any subdirectory.  You would just have to add the repo as either a submodule or subtree and then configure it.  I tested it using a submodule.

I actually had the `continuous-delivery` submodule with an added toc.yaml as part of the PR, but it was kind of messy, so I broke it apart.  I'm learning to dislike submodules.  Subtree isn't always included in git by default, but I was going to see if it was any cleaner.  Do you have any preference, subtree or submodule?

**Pull request merged**
