### PR TITLE
Add content from data-science-workflow repo

### PR DESCRIPTION
**Pull request by MichaelClifford**
This PR is related to [this issue](https://github.com/aicoe-aiops/data-science-workflows/issues/21) in the data science workflow repo.

This is an initial PR to set up https://github.com/aicoe-aiops/data-science-workflows.git as a remote content source for the operate first website. 

It adds a new drop down section to the table of contents called "Data Science Workflow", that currently contains the "getting started" and "project template" docs. The larger "project structure" document needs a small amount of editing to make it relevent to the Op1st audience, I will include those changes in a forthcoming PR. 

Please see an example here: https://michaelclifford.github.io/operate-first.github.io/operate-first

### CODE REVIEW

**Review by tumido — APPROVED** [review]
LGTM :+1:

**Review by oindrillac — COMMENTED** [review]
@MichaelClifford currently the urls in `data-science-workflow-overview` document point to raw documents since gastby is unable to render the github rel urls (eg. https://michaelclifford.github.io/operate-first.github.io/15389585e77686de88b953d59829b42f/project-structure.md). Please be aware that the urls would point to unrendered docs for now

This is being looked into #55 

I think the options here are to:

1. Merge for now and let the urls point to the raw docs until we find a fix
2. Change the rel urls in github to the complete https url for the github docs themselves
3. Change the rel urls in github to the https url of the rendered Gatsby site
4. Wait for a fix for #55 

I personally prefer option 1. Let me know if you have other ideas, and what you prefer.

**Comment by MichaelClifford** [comment]
@oindrillac thanks for the catch. I noticed this as well. I agree with you, option 1 is the way to go "Merge for now and let the urls point to the raw docs until we find a fix", especially as these are remote docs. If I change the relative links, someone browsing the repo on github would be redirected to op1st website, which I dont think is ideal behavior.

**Review by oindrillac — APPROVED** [review]
:ship:

**Pull request merged**
