### PR TITLE
chore: Remove/simplify scripts, deployment templates

### PR DESCRIPTION
**Pull request by tumido**
This PR does a bit of a cleanup in the repo:

- Removes `scripts` and `Makefile`
- Replaces deploy-fork by netlify (let's see if/how that works)
- Removes build and deploy cor container builds, since it's not needed anymore
- Updates readme and travis yaml accordingly.
- Adds `.nvmrc` to force Node 12

This PR aims to simplify and streamline the dev process a bit by using rather common and well known commands instead of a custom scripts and toolkit built around a simple npm scripts...

### CODE REVIEW

**Review by durandom — APPROVED** [review]
LGTM. less code is always better. And indeed, the need for an openshift deployment of the site is no longer needed

**Review by isabelizimm — APPROVED** [review]
/lgtm

**Pull request merged**
