### PR TITLE
Modified command to output local branch

### LINKED ISSUE #62: Unable to view changes on github pages branch
I am unable to preview my changes on my fork's branch

* Here's my github fork [master](https://github.com/oindrillac/operate-first.github.io.git) and as i do `make gh-pages-fork` I am able to view my changes on gh pages [https://oindrillac.github.io/operate-first.github.io/operate-first/](https://oindrillac.github.io/operate-first.github.io/operate-first/).

* However, on my [branch](https://github.com/oindrillac/operate-first.github.io/tree/test) as I do `make gh-pages-branch`, I do not see my changes as I go to [https://oindrillac.github.io/operate-first.github.io/test/](https://oindrillac.github.io/operate-first.github.io/test/)

I am referring the instructions [here](https://github.com/oindrillac/operate-first.github.io#previewing-your-changes-on-github-pages). Am I missing some steps out?

cc: @tumido @cfchase

### PR DESCRIPTION
**Pull request by oindrillac**
This PR changes the instance of `git branch --show-current` in the repo. This addresses #62 
Test Preview is here : https://oindrillac.github.io/operate-first.github.io/master/

Thanks for the help @tumido, @cfchase

### CODE REVIEW

**Review by tumido — APPROVED** [review]
LGTM :+1:

**Comment by tumido** [comment]
This change fixes #62 It turned out that `git branch --show-current` is unavailable in older git and therefore our script broke for `git<2.22`.

As per our chat with @cfchase and @oindrillac we were discussing if we want to keep the branch previews soft-locked to a branch or locked to a precise commit. Currently we build the result into a folder within the `gh-branch` and this folder is named after the previewed branch (and the very same name is used in the url).

Since the content of branch, PR, may change, the preview may not be up to date. Instead we can point and deploy it to a commit hash folder, so you'd immediately know if the preview is at the current PR HEAD or not. On the other hand it'll lower the readability of the url and the same link will not get you to the updated builds, which is also an important aspect. What do you think about that?

This is just a question if we should use `git rev-parse --abbrev-ref HEAD` or `git rev-parse --short HEAD` basically.

cc @durandom

**Review by hemajv — APPROVED** [review]

**Comment by oindrillac** [comment]
@tumido I do not have a strong preference here. However, I'm +1 for importance readability of the urls in the test previews.

**Comment by durandom** [comment]
> the same link will not get you to the updated builds

won't the build be updated upon force-push of the branch? 
If that's not the case, I suggest to use the commit-sha in the URL
a `/branch_name` URL should have the latest content of the branch, that's what I'm expecting.

always default to the least surprise

**Review by cfchase — APPROVED** [review]

**Comment by tumido** [comment]
@durandom a force push on the PR branch will not get it rebuilt, becuase it's not being build by CI.

The only way to update it is for the developer to actually runs the `make gh-pages-branch` command, which they may forget to do after every change on their PR. :/

**Pull request merged**
