### PR TITLE
Switch hitchiker with handbook, and add remote link support.

### LINKED ISSUE #1406: Majority of operate-first.cloud pages are not found
Most webpages that are linked in the side nav do not direct to anything for me.

Examples:
- https://www.operate-first.cloud/hitchhikers-guide/apps/docs/acme/issuing_certificates.md
- https://www.operate-first.cloud/hitchhikers-guide/apps/docs/acm/adding_users_to_acm.md
- https://www.operate-first.cloud/hitchhikers-guide/apps/docs/ocs/claiming_object_store.md

### PR DESCRIPTION
**Pull request by HumairAK**
As per: https://github.com/operate-first/SRE/issues/424#issuecomment-970422981 
Will resolve: https://github.com/operate-first/apps/issues/1406

This is by no means a finalized version of the ToC, but to clean up what currently exists and start moving us in the right direction. 

Changes: 

- I've rebranded HitchHiker's Guide section as "Community Handbook", replaced the intro with the handbook intro, and added a link to our gitops docs (docs for apps repo). 
- There were some links that were linking to demos/tutorials not hosted in operate-first org, I wasn't sure where to put these so I put them  under "Demos". 
- I also removed the datascience workflows from config that was pointing to this section, as it wasn't getting used, and is instead used in the data science section. 
- Added support for remote linking from the site. It's a bit of an ad-hoc implementation to unblock this pr, so that we may link to the jupyterbook from the site in the nav side bar.

Ninja changes  that I snuck in:
- Removed isabel from owners file as she's no longer on the team
- Added a fix flag for es lint (it's annoying trying to read their weird syntax for changes required, this will just try to fix it for you)

### CODE REVIEW

**Comment by HumairAK** [comment]
```
12:46:35 PM: Build exceeded maximum allowed runtime
12:47:59 PM: Error cloning repository: https://github.com/operate-first/operate-first.github.io
```
well then...

**Comment by HumairAK** [comment]
@tumido how can we retry this build?

**Comment by quaid** [comment]
Cool, I'll ack this after a few comments:

> This is by no means a finalized version of the ToC, but to clean up what currently exists and start moving us in the right direction.

This looks really good, and it's helping clarify how to think about the Community Handbook and site layout.

For site layout, I opened [Website map for Dec 2021 changes](https://github.com/operate-first/community/issues/103).

For layout (table of contents basically) within the Community Handbook, it sounds like you are defining and renaming what is effectively a sub-section of the Handbook focused on getting things done when operating the Op1st community cloud. Is that a fair way to view it? Then we can have all the ToC work in that area done by experts/experienced, and we can get reviews from the non-experienced people to provide the new-person perspective.

Then I'd like us to open a PR to hook in pages in `operate-first/community-handbook/` including the overall entire Handbook ToC. What we want to see is the link on the website to the top level of Community Handbook should link to a ToC and introduction that's maintained in `operate-first/community-handbook/`. (And all the sub-directories of indices and markdown pages should be automatically built into the website under Community Handbook.) 

Maybe we can meet on Slack and do that coordination?

> Changes:
> 
> * I've rebranded HitchHiker's Guide section as "Community Handbook", replaced the intro with the handbook intro, and added a link to our gitops docs (docs for apps repo).

Yeah, this is fine as we evolve I think, but I'd like to see us moving to the above approach (or similar) for setting up the Community Handbook.

As a large-scale sophisticated example, here is the Ops Sub-department page at GitLab:  https://about.gitlab.com/handbook/engineering/development/ops/

If we imagine what an Operations SIG for Op1st would look like? It would have some of the similar organizational, process, and communication information, certainly. But it would also have a full library of GitOps reference pages and comprehensive how-we-do-things pages (that can/should be Jupyter notebooks, it's seeming.)

/lgtm

**Comment by HumairAK** [comment]
/hold

Need to fix a few things, the TOC should not have been removed for the 3 tabs

**Comment by HumairAK** [comment]
Preview is up 
@durandom @quaid can you guys take a look: https://deploy-preview-336--relaxed-goldstine-ebb96e.netlify.app/

**Comment by HumairAK** [comment]
Side note: we need a follow up PR that updates this page: https://github.com/HumairAK/operate-first.github.io/blob/community_hb/content/community-handbook/index.md

As that is a content update, I do not think it belongs to this PR. I think that's something better suited for @quaid or someone more involved with the over arching handbook initiative to change :)

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Comment by quaid** [comment]
> Preview is up 
> @durandom @quaid can you guys take a look: https://deploy-preview-336--relaxed-goldstine-ebb96e.netlify.app/ 

I have one question I'll put in as a comment on the commit, no fixes to the PR. This looks very good and I see how straightforward it is building the ToC in the yaml file, how to pull in from across the repos, and so forth.

/lgtm
/approve

**Comment by quaid** [comment]
> > Preview is up 
> > @durandom @quaid can you guys take a look: https://deploy-preview-336--relaxed-goldstine-ebb96e.netlify.app/ 
> 
> I have one question I'll put in as a comment on the commit, no fixes to the PR. This looks very good and I see how straightforward it is building the ToC in the yaml file, how to pull in from across the repos, and so forth.
> 
> /lgtm
> /approve

The question I had is about ‘community-docs.yaml’, line 7 calls something about git docs that doesn't appear in your preview build. What is happening there?

**Comment by HumairAK** [comment]
@quaid not sure what file is that, I don't see it -- can you link to the file/line?

**Review by 4n4nd — APPROVED** [review]

**Pull request merged**
