### PR TITLE
feat: Add twitter icon

### LINKED ISSUE #243: Add twitter icon to top bar panel

### PR DESCRIPTION
**Pull request by tumido**
Resolves: https://github.com/operate-first/operate-first.github.io/issues/243

### CODE REVIEW

**Review by oindrillac — COMMENTED** [review]
/lgtm
/approve

**Review by isabelizimm — APPROVED** [review]
/lgtm

**Comment by durandom** [comment]
@harshad16 can you investigate why @sesheta is not applying `approved` labels and not merging?

**Comment by harshad16** [comment]
> can you investigate why @sesheta is not applying `approved` labels and not merging?

@durandom  yes, we had filed an issue regarding this yesterday.
https://github.com/thoth-station/thoth-application/issues/2058
and investigating on it, why it isn't working.

**Comment by tumido** [comment]
Prow not merging this repo, so I'm gonna merge it manually. :slightly_smiling_face:

**Pull request merged**
