### PR TITLE
Fix broken links and restructure for hitchikers page.

### PR DESCRIPTION
**Pull request by HumairAK**
This PR does the following: 
- Combines "Users" and "Operations" tab under the "Hithiker's Guide" tab 
- Updates a number of broken links on the front page, and within the different  sections 
- Adds various new docs to the website that were not there previously
- Removes unused github repos from the gatsby config 
- Re-organizes the gatsby config a little bit, grouping repos by org

### CODE REVIEW

**Review by oindrillac — APPROVED** [review]
/lgtm
/approve

**Review by 4n4nd — APPROVED** [review]
/lgtm

Looks great 👍

**Comment by durandom** [comment]
I think it's great, but I'd like to have the guide as a standalone JupyterBook deployed somewhere and then link to it from https://www.operate-first.cloud/

Obviously depends on https://github.com/operate-first/hitchhikers-guide/issues/112

**Pull request merged**
