### PR TITLE
change project url to ai4ci

### PR DESCRIPTION
**Pull request by oindrillac**

### CODE REVIEW

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm

**Comment by oindrillac** [comment]
we're getting pod scheduling timeout errors here which were not fixed y https://github.com/operate-first/operate-first.github.io/pull/306
@harshad16 could you please advise?

**Comment by harshad16** [comment]
working on it @oindrillac 
hopefully we will get back the ci

**Review by chauhankaranraj — APPROVED** [review]
/lgtm

**Comment by oindrillac** [comment]
thanks @harshad16 
/approve

**Pull request merged**
