### PR TITLE
re-arrange data science config

### PR DESCRIPTION
**Pull request by oindrillac**
Re-arranged data science left hand toc to bring "Get Involved" at the top and ordered other projects alphabetically.

### CODE REVIEW

**Review by aakankshaduggal — COMMENTED** [review]
I think you're missing a new line at the end. Otherwise, lgtm

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm
/approve

**Comment by MichaelClifford** [comment]
@oindrillac is there an issue you can link this PR to?

**Comment by oindrillac** [comment]
@MichaelClifford sorry there is no issue for this afaik, the toc was out of alphabetical order, so rearranged it and brought the Get Involved call-to-action at the top of the list for higher visibility. Please let me know if you have any thoughts.

**Comment by MichaelClifford** [comment]
:+1: Cool thanks. I just have a larger overhaul of DS portion of the site on the back burner and was wondering if parallel work was being tracked somewhere :)

**Pull request merged**
