### PR TITLE
Add continuous deployment docs

### PR DESCRIPTION
**Pull request by hemajv**
Adding continuous deployment docs (#38)
You can view the changes here: https://hemajv.github.io/operate-first.github.io/

@cfchase Links within docs do not seem to get rendered. For eg in https://hemajv.github.io/operate-first.github.io/cd-quicklab/odh-install-quicklab:
1. there is a link for "CRC" which should point to https://hemajv.github.io/operate-first.github.io/cd-crc/odh-install-crc, but currently it displays `Not Found` error
2. there is a link for "quicklab guide" which should point to https://hemajv.github.io/operate-first.github.io/cd-quicklab/quicklab, but currently takes us to an unrendered doc (https://hemajv.github.io/operate-first.github.io/7fb3928919f32e906f3fe0dd38c98dbd/quicklab.md)

should I be structuring the directories in a different way?

### CODE REVIEW

**Comment by hemajv** [comment]
I also see that the images aren't getting rendered. I have placed all the images in the same directory path as the `.md` files, such as https://github.com/hemajv/continuous-deployment/tree/master/docs/installation_guides/crc

**Comment by oindrillac** [comment]
> Adding continuous deployment docs (#38)
> You can view the changes here: https://hemajv.github.io/operate-first.github.io/
> 
> @cfchase Links within docs do not seem to get rendered. For eg in https://hemajv.github.io/operate-first.github.io/cd-quicklab/odh-install-quicklab:
> 
> 1. there is a link for "CRC" which should point to https://hemajv.github.io/operate-first.github.io/cd-crc/odh-install-crc, but currently it displays `Not Found` error
> 2. there is a link for "quicklab guide" which should point to https://hemajv.github.io/operate-first.github.io/cd-quicklab/quicklab, but currently takes us to an unrendered doc (https://hemajv.github.io/operate-first.github.io/7fb3928919f32e906f3fe0dd38c98dbd/quicklab.md)
> 
> should I be structuring the directories in a different way?

As for the difference in the way the github relative links are behaving upon rendering, i think for the first url for CRC, `[CRC](../crc/odh-install-crc.md)`, is unable to navigate to the crc docs since that is a separate content source directory as per the definition in the [content-sources.yaml](https://github.com/hemajv/operate-first.github.io/blob/master/content-sources.yaml).

As for the second url to the quicklab guide, since the doc is within the same content source directory, we are able to point to the unrendered doc. I am not sure if we have a better way to point to relative urls other than explicitly pointing to the rendered url on the website. @cfchase, do you have any ideas on how this can be attained easily?

As per our discussion in #52 is it better to point to the whole `/docs` directory and add checks on the repos for inconsistent files to avoid the issues similar to whats happening in the CRC url?

**Comment by oindrillac** [comment]
> I also see that the images aren't getting rendered. I have placed all the images in the same directory path as the `.md` files, such as https://github.com/hemajv/continuous-deployment/tree/master/docs/installation_guides/crc

@hemajv I am able to see the rendered image in this doc. I am building from your fork. Do images still not render for you?

image

**Comment by hemajv** [comment]
> > I also see that the images aren't getting rendered. I have placed all the images in the same directory path as the `.md` files, such as https://github.com/hemajv/continuous-deployment/tree/master/docs/installation_guides/crc
> 
> @hemajv I am able to see the rendered image in this doc. I am building from your fork. Do images still not render for you?
> 
> image

yes they render now! :+1:  turns out I didn't fetch the latest changes from my fork

**Comment by durandom** [comment]
@hemajv does this only need a rebase? What's the status?

**Comment by hemajv** [comment]
@oindrillac @aakankshaduggal this is now ready for review. As discussed, adding the `continuous-deployment` docs by pointing the remote repo to the whole `/docs` directory. You can view the changes here: https://hemajv.github.io/operate-first.github.io/master/operate-first/

The docs have been added under the following nav bars:
1. ArgoCD Operations
2. CRC
3. Quicklab

Screenshot from 2020-11-18 15-05-01

**Review by aakankshaduggal — APPROVED** [review]
:ship:

**Pull request merged**
